/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.CommunityResident;

/**
 *
 * @author adepu
 */
public class CommunityResidentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CommunityResident
     */
    public CommunityResidentJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnutcomplaint = new javax.swing.JButton();
        btnemereq = new javax.swing.JButton();
        btnstatuscheck = new javax.swing.JButton();
        btnutcomplaint2 = new javax.swing.JButton();
        btnemereq1 = new javax.swing.JButton();

        btnutcomplaint.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnutcomplaint.setText("UTILITY COMPLAINT");

        btnemereq.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnemereq.setText("SAFETY REQUEST");

        btnstatuscheck.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnstatuscheck.setText("STATUS CHECK");

        btnutcomplaint2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnutcomplaint2.setText("DOCTOR APPOINTMENT");

        btnemereq1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnemereq1.setText("Lab Appointment");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(248, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnutcomplaint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnemereq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnstatuscheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnutcomplaint2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnemereq1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(219, 219, 219))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(btnutcomplaint)
                .addGap(73, 73, 73)
                .addComponent(btnemereq)
                .addGap(53, 53, 53)
                .addComponent(btnutcomplaint2)
                .addGap(72, 72, 72)
                .addComponent(btnemereq1)
                .addGap(99, 99, 99)
                .addComponent(btnstatuscheck)
                .addContainerGap(61, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnemereq;
    private javax.swing.JButton btnemereq1;
    private javax.swing.JButton btnstatuscheck;
    private javax.swing.JButton btnutcomplaint;
    private javax.swing.JButton btnutcomplaint2;
    // End of variables declaration//GEN-END:variables
}
