/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.NonGovernmentManager;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.HelpRequest;
import Business.WorkQueue.WorkAppeal;
import Business.WorkQueue.WorkQueue;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vivek
 */
public class NGOEmployeeJpanel extends javax.swing.JPanel {

    /**
     * Creates new form NonGovernmentJpanel
     */
    JPanel userProcessContainer;
    Enterprise enterprise;
    DefaultTableModel dtm;
    UserAccount userAccount;
    Organization organization;
    int row, col;
    public NGOEmployeeJpanel(JPanel userProcessContainer,UserAccount userAccount, Organization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.organization = organization;
        
        dtm = (DefaultTableModel) tblNGOmngr.getModel();
        lblNGO.setText("Welcome Manager " + userAccount.getEmployee().getName() + ", please manage NGO Organization requests !!" );
        
        PopulateTable();
        populateAmountField();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblNGOmngr = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtamm = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblNGO = new javax.swing.JLabel();

        tblNGOmngr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Resident Name", "Comments", "", "Bank Account no", "Status", "Request Date", "Resolve Date"
            }
        ));
        jScrollPane1.setViewportView(tblNGOmngr);
        if (tblNGOmngr.getColumnModel().getColumnCount() > 0) {
            tblNGOmngr.getColumnModel().getColumn(2).setResizable(false);
        }

        jButton1.setText("Accept");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Decline");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Send Ammount");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtamm.setText("jTextField1");

        jLabel1.setText("Ammount");

        lblNGO.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(jButton1)
                                .addGap(158, 158, 158)
                                .addComponent(jButton2)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtamm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3)
                            .addGap(23, 23, 23)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(lblNGO)))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lblNGO)
                .addGap(59, 59, 59)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jButton2)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtamm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        row = tblNGOmngr.getSelectedRow();
        
        String currentStatus = dtm.getValueAt(row, 4).toString();
        
        if(currentStatus.equalsIgnoreCase("Amount requested"))
        {

            organization.getWorkQueue().getListOfWorkQueues().get(row).setStatus("Request for money is Accepted");

            JOptionPane.showMessageDialog(this, "Money request is Accepted", " money request Accepted", 1);
           
        }
        
        else if(currentStatus.equalsIgnoreCase("Amount request Declined")){
            
            JOptionPane.showMessageDialog(this, "This request is Already declined earlier", " Complaint declined", 1);
            
            
        }
        else{
            JOptionPane.showMessageDialog(this, "Amount request is already accepted", " amount request Accepted", 1);
            
        }
        PopulateTable();
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        row = tblNGOmngr.getSelectedRow();
        
        String currentStatus = dtm.getValueAt(row, 4).toString();
        
        if(currentStatus.equalsIgnoreCase("Amount requested"))
        {

            organization.getWorkQueue().getListOfWorkQueues().get(row).setStatus("Amount request Declined");

            JOptionPane.showMessageDialog(this, "Money request is Declined", " money request declined", 1);
           
        }
        
        else if(currentStatus.equalsIgnoreCase("Amount request Declined")){
            
            JOptionPane.showMessageDialog(this, "This request is Already declined earlier", " Complaint declined", 1);
            
            
        } 
        else{
            JOptionPane.showMessageDialog(this, "Amount request is already accepted", " amount request Accepted", 1);
            
        }
        PopulateTable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         
        row = tblNGOmngr.getSelectedRow();
        
        String currentStatus = dtm.getValueAt(row, 4).toString();
        
        if(currentStatus.equalsIgnoreCase("Amount requested"))
        {

            organization.getWorkQueue().getListOfWorkQueues().get(row).setStatus("Amount request Declined");

            JOptionPane.showMessageDialog(this, "Money request is Declined", " money request declined", 1);
           
        }
        
        else if(currentStatus.equalsIgnoreCase("Amount request Declined")){
            
            JOptionPane.showMessageDialog(this, "This request is Already declined earlier", " Complaint declined", 1);
            
            
        } 
        else{
            JOptionPane.showMessageDialog(this, "Amount request is already accepted", " amount request Accepted", 1);
            
        }
        PopulateTable();
                                       
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNGO;
    private javax.swing.JTable tblNGOmngr;
    private javax.swing.JTextField txtamm;
    // End of variables declaration//GEN-END:variables


private void PopulateTable() {
        
        dtm.setRowCount(0);
        
        WorkQueue workQueue = organization.getWorkQueue();
        
        for(WorkAppeal workRequest  : workQueue.getListOfWorkQueues() ){
            HelpRequest helpRequest = (HelpRequest) workRequest;
            
            
            
            Date date = null;
            if(helpRequest.getStatus().equalsIgnoreCase("Money sent successfully")) {
                  date = helpRequest.getResolveDate();
            }

            Object[] objs = {helpRequest.getSender().getResident().getName(), helpRequest.getHelpComments(), helpRequest.getAmount(), helpRequest.getAccountNumber(), helpRequest.getStatus(), helpRequest.getRequestDate(),helpRequest.getResolveDate()};
            dtm.addRow(objs);
            
        }
       
       
    }

    private void populateAmountField() {
       
        System.out.println(organization.getNgoAvailableFunds());
        txtamm.setText(String.valueOf(this.organization.getNgoAvailableFunds()));
        
    }
  }
