/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.CommunityResident;

import Business.Enterprise.Enterprise;
import static Business.Enterprise.Enterprise.EnterpriseType.Help;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.HelpRequest;
import Business.WorkQueue.WorkAppeal;
import Business.WorkQueue.WorkQueue;
import java.awt.CardLayout;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author adepu
 */
public class HelpRequestJpanel extends javax.swing.JPanel {

    /**
     * Creates new form RaiseDoctorAppointmentRequest
     */
     private JPanel userProcessContainer;
    private Network network ;
    private UserAccount userAccount;
    DefaultTableModel dtm;
    
    public HelpRequestJpanel(JPanel userProcessContainer,UserAccount userAccount, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.network=network;
        this.userAccount = userAccount;
        dtm = (DefaultTableModel) tblhelprequest.getModel();
        populateOrganizations();
        populateTable();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtammount = new javax.swing.JTextField();
        btnsubmit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtcomments = new javax.swing.JTextField();
        btnsubmit1 = new javax.swing.JButton();
        ComboHelpRequestbox = new javax.swing.JComboBox<>();
        txtBankacc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblhelprequest = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setText("HELP  REQUEST");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("REQUEST HELP FROM");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Ammount");

        btnsubmit.setText("Submit Request");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("comments");

        btnsubmit1.setText("Back");
        btnsubmit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmit1ActionPerformed(evt);
            }
        });

        ComboHelpRequestbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboHelpRequestbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboHelpRequestboxActionPerformed(evt);
            }
        });

        txtBankacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBankaccActionPerformed(evt);
            }
        });

        jLabel5.setText("Bank Account Number");

        tblhelprequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Help from", "Comments ", "Amount ", "Bank Account number ", "Status ", "Request Date ", "Resolve Date"
            }
        ));
        jScrollPane1.setViewportView(tblhelprequest);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnsubmit1)
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtcomments, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnsubmit, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(125, 125, 125)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ComboHelpRequestbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtammount, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtBankacc, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(170, 170, 170))
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnsubmit1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(ComboHelpRequestbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtammount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(73, 73, 73))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBankacc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcomments, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(btnsubmit)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBankaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBankaccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBankaccActionPerformed

    private void ComboHelpRequestboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboHelpRequestboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboHelpRequestboxActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        // TODO add your handling code here:
         Organization requestHelpFrom = (Organization) ComboHelpRequestbox.getSelectedItem();
        
        String helpComments = txtcomments.getText();
        
        String amount = txtammount.getText();
        String bankAccountNumber = txtBankacc.getText();
        
        if (!validAccount(bankAccountNumber))
        {
            JOptionPane.showMessageDialog(null, "Invalid account number");
            return;
        }
        
        double doubleAmount = Double.parseDouble(amount);
        
        HelpRequest helpRequest = new HelpRequest();
        helpRequest.setOrganizationType(requestHelpFrom.toString());
        helpRequest.setHelpComments(helpComments);
        helpRequest.setAmount(doubleAmount);
        helpRequest.setAccountNumber(bankAccountNumber);
        helpRequest.setSender(userAccount);
        helpRequest.setRequestDate(new Date());
        helpRequest.setStatus("Amount requested");
        helpRequest.setRequestType("CovidHelp");

        userAccount.getWorkQueue().addWorkAppeal(helpRequest);
        
        requestHelpFrom.getWorkQueue().addWorkAppeal(helpRequest);
        
        
        populateTable();
       
        JOptionPane.showMessageDialog(this, "Request for amount placed successfully !!", "Request", 1);
        ComboHelpRequestbox.setSelectedIndex(0);
        txtammount.setText("");
        txtBankacc.setText("");
        txtcomments.setText("");
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void btnsubmit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmit1ActionPerformed
        // TODO add your handling code here:
          
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnsubmit1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboHelpRequestbox;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JButton btnsubmit1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblhelprequest;
    private javax.swing.JTextField txtBankacc;
    private javax.swing.JTextField txtammount;
    private javax.swing.JTextField txtcomments;
    // End of variables declaration//GEN-END:variables


    private void populateOrganizations() {
         for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()){
            if(e.getEnterpriseType().equals(Help)){
                for(Organization org : e.organizationDirectory.getOrganizationList()){
                    ComboHelpRequestbox.addItem(org.getName());
                }
                
            }
        }
    }
    public Boolean validAccount(String ID) {
        String regex = "^([0-9]{12})$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(ID);
        if(matcher.matches()){  
            return true;
        }
       return false; 
    }
    private void populateTable() {
        
        dtm.setRowCount(0);
  
        WorkQueue workQueue = userAccount.getWorkQueue();
        
        for(WorkAppeal workAppeal  : workQueue.getListOfWorkQueues() ){
           if(workAppeal.getRequestType().equalsIgnoreCase("Help"))
            {
                HelpRequest helpRequest = (HelpRequest) workAppeal;
                
                Date date = null;
                if(helpRequest.getStatus().equalsIgnoreCase("Money sent successfully")) {
                      date = helpRequest.getResolveDate();
                }

                Object[] objs = {helpRequest.getOrganizationType(),helpRequest.getHelpComments(),helpRequest.getAmount(),helpRequest.getAccountNumber(),helpRequest.getStatus(), helpRequest.getRequestDate(),date};
                dtm.addRow(objs);

            }
        }
    }








}
